import { NextResponse } from 'next/server';

export const dynamic = 'force-static';

export async function GET() {
    try {
        // We import the JSON data generated by our Firebase Upload script.
        // During Firebase App Hosting deployment, it simply serves this data!
        const galleryData = await import('@/data/gallery.json');
        
        return NextResponse.json(galleryData.default || galleryData);
    } catch (error) {
        console.error('Error reading gallery data:', error);
        return NextResponse.json({ error: 'Failed to read gallery data. Make sure to run the upload script first.' }, { status: 500 });
    }
}
